### ISSUE TITLE
on_wpid_map_change.yml run failing - possible fix

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pfocr-database#1]
The on_wpid_map_change.yml workflow is failing, the original error was due to an update in r-lib (master branch no longer there), but after that was fixed there is another error:

Error in updateFrontmatter("wpid", "wpid_map") : 
  could not find function "updateFrontmatter"
Execution halted

The corresponding lines in the [yml](https://github.com/wikipathways/pfocr-database/blob/main/.github/workflows/on_wpid_map_change.yml) are (line 36,37):

  Rscript -e 'source("_rmd/updatefm.R")'
  Rscript -e 'updateFrontmatter("wpid", "wpid_map")'

The second line seems wrong to me, since "updateFrontmatter" is just a function in "updatefm.R". Wouldn't that have to be called from inside the script? Currently the [updatefm.R script](https://github.com/wikipathways/pfocr-database/blob/main/_rmd/updatefm.R) only contains two functions, nothing else.

Anyway, after some testing, I think I have a solution. Proposal:

Add to on_wpid_map_change.yml, in stats-update job:
```
env:
  input_file: _data/wpid_map.tsv
env: 
  update_field: wpid
```

Add to updatefm.R, after functions:
`updateFrontmatter(Sys.getenv("update_field"), Sys.getenv("input_file"))`

The same would go for the corresponding [on_ndex_map_change.yml](https://github.com/wikipathways/pfocr-database/blob/main/.github/workflows/on_ndex_map_change.yml). @AlexanderPico : Can you review?

**Comment by AlexanderPico** [comment]
So, if you were running these lines in RStudio Console, they would work fine:

```
source("_rmd/updatefm.R")
updateFrontmatter("wpid", "wpid_map")
```

The logic is that `source` runs the code in updatefm.R which defines two new functions. The next line simply runs the newly defined function.

Using `RScript -e` allows you to run single lines of R code from a terminal. However, you can't use this pattern to run consecutive lines of R code that depend on the same working environment. **_I didn't know that! This was my mistake._**

The fix is to use another approach to running two consecutive lines of R code, and that it:
```
run: |
    source("_rmd/updatefm.R")
    updateFrontmatter("wpid", "wpid_map")
  shell: Rscript {0} 
```
which you can imagine sets up an R environment for those two lines to run in. 

I checked it in and ran it once. I think it's fixed now.

**Comment by AlexanderPico** [comment]
Reopen in case you want to try the same fix for the other action...

**Comment by khanspers** [comment]
Aha! I was actually thinking at first that maybe that the first line just defines the functions, but instead of trying to run it in RStudio console, I was trying to run the two lines exactly how they are written in Terminal (not RStudio). Which didnt work for me. 

It all makes sense now. I will update the other action.
